spring:
    datasource:
        url: ${DEV_DB_URL}        # using environment variables from .env
        username: ${DEV_DB_USERNAME}                       
        password: ${DEV_DB_PASSWORD}           
        driver-class-name: ${DEV_DB_DRIVER}

    jpa:
        database-platform: ${DEV_DB_PLATFORM}
        defer-datasource-initialization: true                   # tells JPA to wait until hibernate is initialized before loading H2 data

server:
    port: 8080      # overriding port set in generic .yml


frontend:
    url: ${DEV_FRONTEND_URL}